config/routes.rb
MeroCms::Engine.routes.draw do
  resources :pages
end

app/models/mero_cms/page.rb
module MeroCms
  class Page < ActiveRecord::Base
    
    validates :title, 
              :presence => true,
              :format => { :with => /^[a-zA-Z0-9\-,' ]+$/ }
    validates :content, :presence => true
  end
end

app/controllers/mero_cms/application_controller.rb
module MeroCms
  class ApplicationController < ::ActionController::Base
    
    def current_mero_cms_user
      binding.pry
      send(:current_user)
    end
    
    helper_method :current_mero_cms_user
    
    def authenticate_and_authorize_mero_cms_user!
      if !current_mero_cms_user
        flash[:alert] = "You must be authenticated before you can do that."
        redirect_to main_app.send(MeroCms::Engine.login_url) and return
      end
      
      unless current_mero_cms_user.can_manage_mero_cms
        flash[:alert] = "You must be authorized before you can do that."
        redirect_to main_app.send(MeroCms::Engine.unauthorized_url) and return
      end
      
    end
  end
end

app/controllers/mero_cms/pages_controller.rb
module MeroCms
  class PagesController < ApplicationController
    respond_to :html, :json
    
    before_filter :authenticate_and_authorize_mero_cms_user!, :except => [:show, :index]
    
    def index
      @pages = MeroCms::Page.all
      respond_with(@pages)
    end

    def show
      @page = MeroCms::Page.find(params[:id])
      respond_with(@page)
    end

    def new
      @page = MeroCms::Page.new
      respond_with(@page)
    end

    def create
      @page = MeroCms::Page.new(params[:page])
      if @page.save
        flash[:notice] = "Page has been created!"
      end
      respond_with(@page, :location => pages_path)
    end

    def edit
      @page = MeroCms::Page.find(params[:id])
      respond_with(@page)
    end

    def update
      @page = MeroCms::Page.find(params[:id])
      if @page.update_attributes(params[:page])
        flash[:notice] = "Page updated!"
      else
        flash[:alert] = "Page could not be updated!"
      end
      respond_with(@page, :location => page_path(@page))
    end

    def destroy
      @page = MeroCms::Page.find(params[:id])
      @page.destroy
      flash[:notice] = "Page destroyed!"
      respond_with(@page)
    end
  end
end

app/helpers/mero_cms/application_helper.rb
module MeroCms
  module ApplicationHelper
  end
end

app/helpers/mero_cms/pages_helper.rb
module MeroCms
  module PagesHelper
  end
end

app/views/layouts/mero_cms/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mero CMS</title>
  <%= stylesheet_link_tag    "mero_cms/application" %>
  <%= javascript_include_tag "mero_cms/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<% flash.each do |key, message| %> 
  <p id="flash_<%= key %>"><%= message %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/mero_cms/pages/_form.html.erb
<%= form_for @page do |f| -%>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content, :cols => 60, :rows => 7 %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end -%>

app/views/mero_cms/pages/edit.html.erb
<h1>Editing Page</h1>
<%= render "form" %>

app/views/mero_cms/pages/index.html.erb
<h1>Pages</h1>
<%= link_to "New Page", new_page_path %>
<% if @pages.empty? %>
  There are currently no pages.
<% else %>
  <table id="pages">
    <thead>
      <tr>
        <td>Title</td><td>Content</td>
      </tr>
    </thead>
    <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td class="page_title"><%= link_to page.title, page %></td>
        <td class="page_content"><%= link_to page.content, page %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/mero_cms/pages/new.html.erb
<h1>New Page</h1>
<%= render "form" %>

app/views/mero_cms/pages/show.html.erb
<div id="page">
  <h2><%= @page.title %></h2>
  <%= div_for(@page) do %>
    <%= @page.content %>
  <% end %>
  <nav class="actions">
    <%= link_to "Edit", edit_page_path(@page) %>
    <%= link_to "Destroy", page_path(@page), :method => :delete %>
  </nav>
</div>